broken but stair behaviour is in
checking for more messages causes crashes, Navigate needs the lock file too

Got an image index out of range crash, dump below

Traceback (most recent call last):
  File "C:\Users\David\Documents\crawlbot PYTHON\selenium\derpyai\derpyai.py", line 195, in <module>
    state.Update()
  File "C:\Users\David\Documents\crawlbot PYTHON\selenium\derpyai\player_behaviour.py", line 98, in Update
    Behaviour._get_path(self, goals[0])
  File "C:\Users\David\Documents\crawlbot PYTHON\selenium\derpyai\player_behaviour.py", line 22, in _get_path
    self.mypath = self.navigate.get_path(mylocation, goal)
  File "C:\Users\David\Documents\crawlbot PYTHON\selenium\derpyai\navigate.py", line 219, in get_path
    new_node = self._get_a_node(closest_neighbor[0], cheapest_node)
  File "C:\Users\David\Documents\crawlbot PYTHON\selenium\derpyai\navigate.py", line 76, in _get_a_node
    neighbors = self._get_neighbors(coordinates)
  File "C:\Users\David\Documents\crawlbot PYTHON\selenium\derpyai\navigate.py", line 57, in _get_neighbors
    self.MAP_FEATURES[pixels[neighbor_coordinate]])
IndexError: image index out of range